services:
  backend:
    image: project-backend:latest
    container_name: project-backend-v1
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        - SPRING_TRINO_USERNAME=${SPRING_TRINO_USERNAME}
        - SPRING_TRINO_URL=${SPRING_TRINO_URL}
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - CATALOG=${CATALOG}
    networks:
      - my-shared-network

  frontend:
    image: project-frontend:latest
    container_name: project-frontend-v1
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    command: npm start
    networks:
      - my-shared-network

networks:
  my-shared-network:
    external: true
