services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: oracle-db
    env_file:
      - ../.env
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true 
      - ORACLE_PASSWORD=system   
      - ORACLE_USERNAME=system   
      - TZ=Etc/UTC   
      - SPRING_DATASOURCE_USERNAME=my_user
      - SPRING_DATASOURCE_PASSWORD=mypass
    volumes:
      - oracle-data:/u01/app/oracle
      - oracle-logs:/u01/app/oracle/diag
    restart: unless-stopped
    networks:
      - my-shared-network

networks:
  my-shared-network:
    external: true
volumes:
  oracle-data:
  oracle-logs:
